apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pgk6y4af5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/pgk6y4af5-java-quarkus-gitops